# Generated by Django 2.2 on 2019-05-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.CharField(choices=[('Контакты', 'Contacts'), ('Обо мне', 'bio'), ('О портале', 'portal')], max_length=50)),
            ],
        ),
    ]
