# Generated by Django 2.2 on 2019-05-01 11:47

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pagecontent_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='target_page',
            field=models.CharField(choices=[('contacts', 'Контакты'), ('bio', 'Обо мне'), ('portal', 'О портале')], max_length=50),
        ),
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
